### ISSUE TITLE
Support for RGB colors

### ISSUE THREAD

**Issue by sergiocorreia** [mdroste/stata-binscatter2#2] opened 2019-02-13 22:12 UTC
Hi Michael!

First of all, thanks a lot for binscatter2, your improvements and speedups are quite valuable, and something that was needed for a while.

There's a bug in the `mcolor()` option of binscatter, which is also on biscatter2 (it also applies to related options). The culprit is that the syntax string is set as [`mcolors(string)`](https://github.com/mdroste/stata-binscatter2/blob/master/binscatter2.ado#L37) instead of `mcolors(string asis)`.

If you see the [help file](https://www.stata.com/help.cgi?colorstyle) for color styles, it allows stuff like `mcolor("100 100 100")`, where the numbers denote RGB colors. However, if you try to run it, both binscatter and binscatter2 raise an error:

```stata
. sysuse auto, clear
. binscatter price weight, mcolor("4 90 141")
(note:  named style 4 not found in class color, default attributes used)
```

The fix needs changes in only two lines. You can see a diff here: https://www.diffchecker.com/AP957xRL The first change is just to add `asis` to the syntax string, while the second change involves adding quotes to [this line](https://github.com/mdroste/stata-binscatter2/blob/master/binscatter2.ado#L706) (in the way shown in the diffchecker link, on line 558 there.

Thanks!
Sergio

**Comment by mdroste** [comment] 2019-02-14 01:36
Hi Sergio,

Thanks for the support and for pointing this bug out! It's been fixed in the version just posted (0.14).

Best,
Mike

**Closed as completed by mdroste** 2019-02-14 01:36 UTC

**Comment by sergiocorreia** [comment] 2019-02-14 01:38
Thanks! Btw, the same issue might apply with the lcolor() and color() options, although I haven't tested it.

**Comment by mdroste** [comment] 2019-02-14 02:21
Hi Sergio,

You're totally right. I have fixed the issue for lcolors() as well, but the issue is a little trickier for colors(). Since you can use lcolors() and mcolors() to the same effect, I'm going to keep this issue closed for now, but open a new one describing the issue for colors() with lower priority.

**Comment by sergiocorreia** [comment] 2019-02-14 02:30
Great! I'm not even sure of what colors() do exactly that the others don't, so for me lcolors and mcolors are more than enough.

Best,
S
