### ISSUE TITLE
Bug?: conformability error

### ISSUE THREAD

**Issue by santiago-afonso** [mdroste/stata-binscatter2#7] opened 2019-09-13 16:35 UTC
Hello. Thanks for the great work!

This line sometimes generates a mata "conformability error". I have a do file where, on the same exact dataset, the first six times I call binscatter2 work without problems but on the seventh it quits citing this error.

I don't know mata so I can't further pinpoint the source of the problem. The only difference in my dataset between the 6th and 7th call to binscatter2 is that on the last one I add _if sex == 1_ to the call, everything else being the same (one control, one by variable and another if common to both calls that exclude inactive people). The _sex_ variable doesn't have missing values.

https://github.com/mdroste/stata-binscatter2/blob/719ba6fee0832c8f12c5efaba618a8b56eae61d0/binscatter2.ado#L740

**Comment by mdroste** [comment] 2022-12-05 21:21
I see this too, and can reproduce it with simple examples involving by(). I'll explore more today.

**Comment by mdroste** [comment] 2022-12-06 18:00
At long last, I think this bug is fixed! Marking as closed for now because I can no longer reproduce this bug and think my fix will work with any case (essentially, being extra careful about the dimensions of every object and every possible sort order)

**Closed as completed by mdroste** 2022-12-06 18:00 UTC
Labels: bug
